POST http://localhost:8000/threshold
Content-Type: application/json

{
  "userId": "ede2d85a-438d-4be2-9c4b-45e254e9fc34",
  "money": {
    "amount": 500,
    "currency": "GBP"
  },
  "startingFrom": "2022-01-01 11:00:00"
}

###

POST http://localhost:8000/debit
Content-Type: application/json

{
  "userId": "ede2d85a-438d-4be2-9c4b-45e254e9fc34",
  "money": {
    "amount": 200,
    "currency": "GBP"
  },
  "type": "debit",
  "time": "2022-01-02 13:00:00"
}

###

POST http://localhost:8000/credit
Content-Type: application/json

{
  "userId": "ede2d85a-438d-4be2-9c4b-45e254e9fc34",
  "money": {
    "amount": 150,
    "currency": "GBP"
  },
  "type": "credit",
  "time": "2022-01-02 14:00:00"
}
